import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";

// Correct syntax for the Sarabun font
const noto = Noto_Sans_Thai({
  subsets: ["thai"],
  weight: ['400','600','700',],
  variable: "--font-noto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={noto.variable}>{children}</body>
    </html>
  );
}
